.TH MAESTRO 1 2020-08-08 "Maestro v1.0.0"

.SH NAME
maestro \- a framework for working with AWS Step Functions

.SH SYNOPSIS

.PP
.B maestro
.I [help|\-h|\-\-help]

.PP
.B maestro new
[\fB\-n\fR|\fB\-\-no\-template\fR|\fB\-t\fR \fItemplate_name\fR|\fB\-\-template=\fItemplate_name\fR|\fB\-\-template\fR \fItemplate_name\fR]

.PP
.B maestro deploy

.PP
.B maestro teardown
[\fB\-f\fR|\fB\-\-force\fR]
[\fB\-\-roles=\fIrole1\fR[,\fIrole2\fR...\fI]|\fB\-\-roles\fR \fIrole1\fR[,\fIrole2\fR...\fI]]

.SH DESCRIPTION

.SH OPTIONS

.SH ENVIRONMENT

.SH FILES

.SH NOTES

.SH BUGS

.SH EXAMPLE

.SH SEE ALSO
