.TH MAESTRO-TEARDOWN 1 2020-08-08 "Maestro v1.0.0"

.SH NAME

maestro-teardown \- teardown an existing maestro project

.SH SYNOPSIS

.B maestro teardown
[\fB\-f\fR|\fB\-\-force\fR]
[\fB\-\-roles=\fIrole1\fR[,\fIrole2\fR...]|\fB\-\-roles\fR
\fIrole1\fR[,\fIrole2\fR...]]

.SH DESCRIPTION

.SH OPTIONS

.SH NOTES

.SH BUGS

.SH EXAMPLE

.SH SEE ALSO

.BR maestro (1),
.BR maestro-help (1),
.BR maestro-deploy (1),
.BR maestro-new (1),
.BR maestro-get-templates (1)
