.TH MAESTRO-NEW 1 2020-08-08 "Maestro v1.0.0"

.SH NAME

maestro-new \- create a new maestro project

.SH SYNOPSIS

.BI "maestro new " project_name
[\fB\-n\fR|\fB\-\-no\-template\fR|\fB\-t\fR
\fItemplate_name\fR|\fB\-\-template=\fItemplate_name\fR|\fB\-\-template\fR
\fItemplate_name\fR]

.SH DESCRIPTION

.SH OPTIONS

.SH NOTES

.SH BUGS

.SH EXAMPLE

.SH SEE ALSO

.BR maestro (1),
.BR maestro-help (1),
.BR maestro-deploy (1),
.BR maestro-get-templates (1),
.BR maestro-teardown (1)
