.TH MAESTRO-DEPLOY 1 2020-08-08 "Maestro v1.0.0"

.SH NAME

maestro-deploy \- deploy a full AWS Step Functions workflow with AWS
Lambdas

.SH SYNOPSIS

.PP
.B maestro deploy

.SH DESCRIPTION

.SH OPTIONS

.SH NOTES

.SH BUGS

.PP
Since Maestro is in the prototypal phase, bug reports are welcome and can be submitted at
.UR https://github.com/maestro-framework/maestro/issues
the GitHub Issues page
.UE .

.SH EXAMPLE

.SH SEE ALSO

.BR maestro(1),
.BR maestro-help (1),
.BR maestro-config (1),
.BR maestro-new (1),
.BR maestro-get-templates (1),
.BR maestro-teardown (1)
